# Generated by Django 5.2.17 on 2026-09-23 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('live', 'Live')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='sessions/%Y/%m/%d/')),
                ('person_count', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('compliant_count', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g., Gate-01, Workshop-Floor', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Camera IP, e.g., 192.168.1.64')),
                ('port', models.PositiveIntegerField(default=554, help_text='Port: 554 for RTSP, 80/8080 for HTTP')),
                ('protocol', models.CharField(choices=[('rtsp', 'RTSP'), ('rtsp_tcp', 'RTSP/TCP'), ('http', 'HTTP/MJPEG'), ('https', 'HTTPS')], default='rtsp', max_length=10)),
                ('stream_path', models.CharField(default='/stream1', help_text='Path after IP:port, e.g., /stream1, /live/ch1, /video.mjpg', max_length=300)),
                ('username', models.CharField(blank=True, help_text='RTSP/HTTP auth user (optional)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Password (optional, stored plain - use secrets in prod)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location / zone', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this camera')),
                ('detection_enabled', models.BooleanField(default=True, help_text='Run PPE detection on this stream')),
                ('confidence_threshold', models.FloatField(default=0.6, help_text='YOLO confidence for this camera')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Connection Error'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Camera',
                'verbose_name_plural': 'IP Cameras',
                'ordering': ['-is_active', 'name'],
                'unique_together': {('ip_address', 'port', 'stream_path')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('person_id', models.CharField(db_index=True, max_length=64)),
                ('missing_items', models.JSONField(default=list, help_text='List of missing PPE items')),
                ('violation_type', models.CharField(choices=[('DETECTED', 'Detected'), ('RESOLVED', 'Resolved')], default='DETECTED', max_length=10)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds if resolved', null=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violations/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, help_text='Camera that captured this violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='monitor.ipcamera')),
            ],
            options={
                'verbose_name': 'PPE Violation',
                'verbose_name_plural': 'PPE Violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
