# Generated by Django 5.2.17 on 2026-09-23 07:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Workshop A, Gate-1, Warehouse', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical zone: violations trigger immediate alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera Zone',
                'verbose_name_plural': 'Camera Zones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ipcamera',
            options={'ordering': ['-is_active', 'zone__name', 'name'], 'verbose_name': 'IP Camera', 'verbose_name_plural': 'IP Cameras'},
        ),
        migrations.AddField(
            model_name='detectionsession',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='monitor.ipcamera'),
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0, help_text='For circuit-breaker / alert throttling'),
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='uptime_24h',
            field=models.FloatField(default=0.0, help_text='Uptime % last 24h (0-100)'),
        ),
        migrations.AlterField(
            model_name='detectionsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='detectionsession',
            name='session_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('live', 'Live')], db_index=True, default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='confidence_threshold',
            field=models.FloatField(default=0.6, help_text='YOLO confidence for this camera', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Camera IP, e.g., 192.168.1.64 (or hostname if GenericIPAddressField is bypassed via form)'),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable/disable this camera'),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location / zone description', max_length=200),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='name',
            field=models.CharField(help_text='Display name, e.g., Gate-01, Workshop-Floor', max_length=100, validators=[django.core.validators.RegexValidator('^[\\w\\-\\s]+$', 'Use letters, numbers, -, _ and spaces')]),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='password',
            field=models.CharField(blank=True, help_text='Password (encrypted at rest if PPE_FERNET_KEY set)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='port',
            field=models.PositiveIntegerField(default=554, help_text='Port: 554 for RTSP, 80/8080 for HTTP', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='protocol',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('rtsp_tcp', 'RTSP/TCP (reliable)'), ('http', 'HTTP/MJPEG'), ('https', 'HTTPS/MJPEG')], db_index=True, default='rtsp', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Connection Error'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='stream_path',
            field=models.CharField(default='/stream1', help_text='Path after IP:port, e.g., /stream1, /live/ch1, /video.mjpg', max_length=300, validators=[django.core.validators.RegexValidator('^/.*', 'Must start with /')]),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('DETECTED', 'Detected'), ('RESOLVED', 'Resolved')], db_index=True, default='DETECTED', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('test', 'Test'), ('toggle', 'Toggle')], max_length=10)),
                ('entity', models.CharField(help_text='e.g., IPCamera', max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CameraHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_ok', models.BooleanField(db_index=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='monitor.ipcamera')),
            ],
            options={
                'verbose_name': 'Camera Health Log',
                'verbose_name_plural': 'Camera Health Logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone for compliance grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='monitor.camerazone'),
        ),
        migrations.AddField(
            model_name='violation',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Denormalized zone at violation time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='monitor.camerazone'),
        ),
        migrations.AddIndex(
            model_name='ipcamera',
            index=models.Index(fields=['is_active', 'status'], name='monitor_ipc_is_acti_2c0f99_idx'),
        ),
        migrations.AddIndex(
            model_name='ipcamera',
            index=models.Index(fields=['zone', 'is_active'], name='monitor_ipc_zone_id_c6bb89_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['camera', '-timestamp'], name='monitor_vio_camera__507e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['zone', '-timestamp'], name='monitor_vio_zone_id_59ece4_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['violation_type', '-timestamp'], name='monitor_vio_violati_4b973a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipcamera',
            constraint=models.CheckConstraint(condition=models.Q(('port__gte', 1), ('port__lte', 65535)), name='port_range'),
        ),
        migrations.AddConstraint(
            model_name='ipcamera',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_threshold__gte', 0.1), ('confidence_threshold__lte', 1.0)), name='conf_range'),
        ),
        migrations.AddIndex(
            model_name='camerahealthlog',
            index=models.Index(fields=['camera', '-checked_at'], name='monitor_cam_camera__91267c_idx'),
        ),
    ]
